AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'bin/*'

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 75

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBeginBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Next:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
